"use strict";

const fs = require("fs");
const path = require("path");
const { assert } = require("./_helpers");

async function run() {
  const workspaceUi = fs.readFileSync(path.join(process.cwd(), "apps/hub/static/ui/project-workspace.html"), "utf8");
  assert(workspaceUi.includes("Workspace Search"), "workspace search title should exist");
  assert(workspaceUi.includes("workspace-search-form"), "workspace search form should exist");
  assert(workspaceUi.includes("workspace-search-query"), "workspace search query input should exist");
  assert(workspaceUi.includes("workspace-search-status"), "workspace search status filter should exist");
  assert(workspaceUi.includes("workspace-search-provider"), "workspace search provider filter should exist");
  assert(workspaceUi.includes("workspace-search-export"), "workspace search export should exist");
  assert(workspaceUi.includes("workspace-search-export-format"), "workspace search export format should exist");
  assert(workspaceUi.includes("workspace-search-time-from"), "workspace search time_from filter should exist");
  assert(workspaceUi.includes("workspace-search-time-to"), "workspace search time_to filter should exist");
  assert(workspaceUi.includes("workspace-search-scopes"), "workspace search scope toggles should exist");
  assert(workspaceUi.includes('apiPost("/workspace/search"'), "workspace ui should call workspace search api");
  assert(workspaceUi.includes('apiPostDownload("/exports/workspace"'), "workspace ui should call workspace export api");
  assert(workspaceUi.includes("検索結果は 0 件です"), "workspace ui should show zero-state text");
  assert(workspaceUi.includes("validation_error:"), "workspace ui should show validation error text");
  assert(workspaceUi.includes("/ui/project-thread.html?project_id="), "workspace search results should link to thread detail");
  assert(workspaceUi.includes("/ui/run.html?run_id="), "workspace search results should link to run detail");
  assert(workspaceUi.includes("#run-external-audit"), "workspace search results should link to external audit detail");
  assert(workspaceUi.includes("Workspace History"), "workspace history title should exist");
  assert(workspaceUi.includes("workspace-history-form"), "workspace history form should exist");
  assert(workspaceUi.includes("workspace-history-list"), "workspace history list should exist");
  assert(workspaceUi.includes("workspace-history-detail-body"), "workspace history detail should exist");
  assert(workspaceUi.includes("workspace-history-export"), "workspace history export should exist");
  assert(workspaceUi.includes("workspace-history-detail-retry-read"), "workspace history detail read retry should exist");
  assert(workspaceUi.includes("workspace-history-detail-retry-failed"), "workspace history detail failed retry should exist");
  assert(workspaceUi.includes("workspace-history-detail-export"), "workspace history detail export should exist");
  assert(workspaceUi.includes("workspace-history-detail-export-audit"), "workspace history detail audit export should exist");
  assert(workspaceUi.includes("workspace-history-export-format"), "workspace history export format should exist");
  assert(workspaceUi.includes("workspace-history-detail-export-format"), "workspace history detail export format should exist");
  assert(workspaceUi.includes('apiPost("/history"'), "workspace ui should call history api");
  assert(workspaceUi.includes("履歴へ"), "workspace search results should link to history detail");
  assert(workspaceUi.includes("confirm・write・failed・skipped"), "workspace history should highlight confirm/write/failed/skipped context");
  assert(workspaceUi.includes("day_groups"), "workspace history ui should use day_groups");
  assert(workspaceUi.includes("run_summaries"), "workspace history ui should use run summaries");
  assert(workspaceUi.includes("events</span>"), "workspace history ui should render factual event count summaries");
  assert(workspaceUi.includes("Workspace Observability"), "workspace observability title should exist");
  assert(workspaceUi.includes("workspace-metrics-form"), "workspace observability form should exist");
  assert(workspaceUi.includes("workspace-metrics-kpis"), "workspace observability KPI container should exist");
  assert(workspaceUi.includes("workspace-metrics-alerts"), "workspace observability alert container should exist");
  assert(workspaceUi.includes("workspace-metrics-status-distribution"), "workspace observability status distribution should exist");
  assert(workspaceUi.includes("workspace-metrics-provider-counts"), "workspace observability provider counts should exist");
  assert(workspaceUi.includes("workspace-metrics-failure-codes"), "workspace observability failure code container should exist");
  assert(workspaceUi.includes("workspace-metrics-fidelity"), "workspace observability fidelity container should exist");
  assert(workspaceUi.includes("workspace-metrics-timeseries"), "workspace observability timeseries should exist");
  assert(workspaceUi.includes("workspace-metrics-retry-read"), "workspace observability read retry should exist");
  assert(workspaceUi.includes("workspace-metrics-retry-failed"), "workspace observability failed retry should exist");
  assert(workspaceUi.includes("workspace-metrics-export"), "workspace observability export should exist");
  assert(workspaceUi.includes("workspace-metrics-export-format"), "workspace observability export format should exist");
  assert(workspaceUi.includes('apiPost("/metrics/workspace"'), "workspace ui should call workspace metrics api");
  assert(workspaceUi.includes('/retry`'), "workspace ui should call retry api");
  assert(workspaceUi.includes("24h"), "workspace observability should include 24h range toggle");
  assert(workspaceUi.includes("7d"), "workspace observability should include 7d range toggle");
  assert(workspaceUi.includes("30d"), "workspace observability should include 30d range toggle");
  assert(workspaceUi.includes("custom range"), "workspace observability should mention custom range handling");
  assert(workspaceUi.includes("warning / alert"), "workspace observability should show warning/alert state");
  assert(workspaceUi.includes("anomalies.items"), "workspace observability should render anomaly items");
  assert(workspaceUi.includes("retry 不可"), "workspace operability should show retry disabled reasons");
  assert(workspaceUi.includes("export しました"), "workspace operability should show export status");
  assert(workspaceUi.includes("csv"), "workspace ui should expose csv export");
  assert(workspaceUi.includes("json"), "workspace ui should expose json export");

  const runUi = fs.readFileSync(path.join(process.cwd(), "apps/hub/static/ui/run.html"), "utf8");
  assert(runUi.includes("run-external-audit"), "run ui should include external audit anchor");
  assert(runUi.includes("run-external-audit-preview"), "run ui should include external audit preview");
}

module.exports = { run };
