#!/usr/bin/env node
/**
 * pr-up.js  ── Codexサンドボックス（ネットワーク不可）で実行する部分
 *
 * やること:
 *   1. main/master ブランチガード
 *   2. npm test
 *   3. gen-pr-body.js → /tmp/pr.md 生成
 *   4. pr-body-verify.js でバリデーション
 *   5. /tmp/pr-push.sh を生成（push + PR作成コマンドをファイルに書き出す）
 *
 * やらないこと:
 *   - git push（ネットワーク必須）
 *   - gh pr create/edit（ネットワーク必須）
 *
 * ネットワーク必須の手順は /tmp/pr-push.sh に書き出す。
 * ネットワーク可の端末で: bash /tmp/pr-push.sh
 */

const fs = require("fs");
const { spawnSync } = require("child_process");

function sh(cmd, args, opts = {}) {
  return spawnSync(cmd, args, { encoding: "utf8", ...opts });
}

function must(cmd, args, opts = {}) {
  const r = sh(cmd, args, opts);
  if (r.status !== 0) {
    const out = ((r.stdout || "") + "\n" + (r.stderr || "")).trim();
    throw new Error(`${cmd} ${args.join(" ")} failed (code=${r.status})\n${out}`);
  }
  return (r.stdout || "").trim();
}

function info(msg) { process.stdout.write(msg + "\n"); }
function warn(msg) { process.stderr.write(msg + "\n"); }

function getRepoNwo() {
  const r = sh("git", ["remote", "get-url", "origin"]);
  if (r.status !== 0) throw new Error("git remote get-url origin failed: " + (r.stderr || "").trim());
  const url = (r.stdout || "").trim();
  const m = url.match(/github\.com[:/](.+?)(?:\.git)?$/);
  if (m) return m[1];
  throw new Error(`Cannot parse GitHub repo NWO from remote URL: ${url}`);
}

function writePushScript({ branch, repoNwo, title }) {
  const script = [
    "#!/usr/bin/env bash",
    "# Auto-generated by pr-up.js — run this in a network-reachable environment",
    "set -euo pipefail",
    "",
    `REPO="${repoNwo}"`,
    `BRANCH="${branch}"`,
    `TITLE="${title.replace(/"/g, '\\"')}"`,
    `BASE=$(gh repo view "$REPO" --json defaultBranchRef --jq '.defaultBranchRef.name' 2>/dev/null || echo main)`,
    "",
    'echo "[PR-PUSH] repo=$REPO base=$BASE head=$BRANCH"',
    "",
    "# 1. push",
    'git push -u origin "$BRANCH"',
    "",
    "# 2. PR create or update",
    'EXISTING=$(gh pr list --repo "$REPO" --head "$BRANCH" --json number --jq ".[0].number" 2>/dev/null || true)',
    'if [ -n "$EXISTING" ]; then',
    '  gh pr edit "$EXISTING" --repo "$REPO" --body-file /tmp/pr.md',
    '  echo "[PR-PUSH] Updated PR #$EXISTING"',
    'else',
    '  gh pr create --repo "$REPO" --base "$BASE" --head "$BRANCH" --title "$TITLE" --body-file /tmp/pr.md',
    'fi',
  ].join("\n") + "\n";

  fs.writeFileSync("/tmp/pr-push.sh", script, { mode: 0o755 });
}

function main() {
  const branch = must("git", ["rev-parse", "--abbrev-ref", "HEAD"]);
  if (branch === "main" || branch === "master") {
    warn(`[PR-UP] REFUSED: current branch is ${branch}. Create a feature branch first.`);
    warn(`[PR-UP] Next: git checkout -b issue-<number>-<slug>`);
    process.exit(1);
  }

  // ローカルで完結するステップ
  must("npm", ["test"]);
  must("node", ["scripts/gen-pr-body.js"]);
  must("node", ["scripts/pr-body-verify.js", "/tmp/pr.md"]);

  const repoNwo = getRepoNwo();
  const title = must("git", ["log", "-1", "--pretty=%s"]);

  writePushScript({ branch, repoNwo, title });

  info("");
  info("[PR-UP] ✅ Local steps done. /tmp/pr.md and /tmp/pr-push.sh are ready.");
  info("[PR-UP] Network-required steps → run in a network-reachable environment:");
  info(`  bash /tmp/pr-push.sh`);
  info(`  # or manually:`);
  info(`  #   git push -u origin ${branch}`);
  info(`  #   gh pr create --repo ${repoNwo} --base main --head ${branch} --title "${title}" --body-file /tmp/pr.md`);
}

try {
  main();
} catch (e) {
  process.stderr.write(`[PR-UP] FAILED: ${e && e.message ? e.message : String(e)}\n`);
  process.exit(1);
}